services:
#    s_web_user.example:
#        class: SWeb\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    sweb_user.oauth_user_provider:
        class: SWeb\UserBundle\OAuthUserProvider
