home:
    path:     /
    defaults: { _controller: SWebSemanticSocialWebBundle:Home:index }
ontology_visualization:
    path:     /ontology
    defaults: { _controller: SWebSemanticSocialWebBundle:Ontology:index }
sparql_form:
    path:     /sparql
    defaults: { _controller: SWebSemanticSocialWebBundle:SparqlForm:index }
about:
    path:     /about
    defaults: { _controller: SWebSemanticSocialWebBundle:About:index }
