home:
    path:     /
    defaults: { _controller: SWebSemanticSocialWebBundle:Home:index }

predefined_queries:
    path:     /connections
    defaults: { _controller: SWebSemanticSocialWebBundle:PredefinedQueries:index }
predefined_queries_topTen:
    path:     /connections/topTenInterests
    defaults: { _controller: SWebSemanticSocialWebBundle:PredefinedQueries:topTenInterest }
predefined_queries_form:
    path:     /connections/form/{index}
    defaults: { _controller: SWebSemanticSocialWebBundle:PredefinedQueries:form }
predefined_queries_handler:
    path:     /connections/result
    defaults: { _controller: SWebSemanticSocialWebBundle:PredefinedQueries:handle }

ontology_visualization:
    path:     /ontology
    defaults: { _controller: SWebSemanticSocialWebBundle:Ontology:index }
ontology_data:
    path:     /ontology/data
    defaults: { _controller: SWebSemanticSocialWebBundle:Ontology:data }

sparql_form:
    path:     /sparql
    defaults: { _controller: SWebSemanticSocialWebBundle:SparqlForm:index }

about:
    path:     /about
    defaults: { _controller: SWebSemanticSocialWebBundle:About:index }

admin:
    path:     /admin
    defaults: { _controller: SWebSemanticSocialWebBundle:Admin:index }
