s_web_user:
    resource: "@SWebUserBundle/Resources/config/routing.yml"
    prefix:   /

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

google_login:
    pattern: /login/check-google


s_web_semantic_social_web:
    resource: "@SWebSemanticSocialWebBundle/Resources/config/routing.yml"
    prefix:   /

SWebUserBundle:
        resource: "@SWebUserBundle/Resources/config/routing.yml"
        prefix:   /

