security:
    providers:
        in_memory:
            memory: ~
        sweb_hwi_provider:
            id: sweb_user.oauth_user_provider

    firewalls:
        # dev:
        #    pattern: ^/(_(profiler|wdt)|css|images|js)/
        #    security: false

        secured_area:
            anonymous: ~
            oauth:
                resource_owners:
                    google:             "/login/check-google"
                login_path:        /login
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: sweb_user.oauth_user_provider

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
